### ISSUE TITLE
Should `field` support modifications of inherited attributes, like `param` does ?

### ISSUE THREAD

**Issue by gmbow** [Ovid/moosex-extended#51]
In Moose, we can override some aspects of an inherited attribute in a child class by prefixing the attribute name with  `+` in `has`, as shown in [Attribute Inheritance in Moose::Manual::Attributes](https://metacpan.org/pod/Moose::Manual::Attributes#ATTRIBUTE-INHERITANCE).

In MooseX::Modern, it seems like the `+` syntax is supported in `param`, but not in `field` :

```perl
package My::Point {
    use MooseX::Extended types => [qw(Num Defined)];
        
    param [ 'x', 'y' ] => ( isa => Num );
    field 'z' => (isa => Num, default => 1 );
}
 
package My::Point::Mutable {
    use MooseX::Extended;
    extends 'My::Point';
     
    param [ '+x', '+y' ] => ( clearer => 1 );
    field '+z' => (clearer  => 1);
}
``` 
Fails with :
```
Error at /home/g/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0/x86_64-linux/Moose/Util.pm line 48
	Moose::Util::throw_exception('InvalidAttributeDefinition', 'attribute_name', '+z', 'class_name', 'My::Point::Mutable', 'messsage', 'Illegal attribute name, \'+z\'') called at /home/g/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0/MooseX/Extended/Core.pm line 299
	MooseX::Extended::Core::_add_attribute('field', 'Moose::Meta::Class::__ANON__::SERIAL::1=HASH(0x560c49c53080)', '+z', 'init_arg', undef, 'is', 'ro', '_call_level', 1, 'clearer', 1) called at /home/g/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0/MooseX/Extended/Core.pm line 292
	MooseX::Extended::Core::field('Moose::Meta::Class::__ANON__::SERIAL::1=HASH(0x560c49c53080)', '+z', 'clearer', 1) called at /home/g/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0/x86_64-linux/Moose/Exporter.pm line 418
	MooseX::Extended::field('+z', 'clearer', 1) called at test/moosex_extended.pl line 13
```

Is this on purpose?

I am running perl 5.36 on Ubuntu 20.04.

**Comment by Ovid** [comment]
It is not on purpose. I genuinely missed that!

That being said, here's a concern:

```perl
package My::Point {
    use MooseX::Extended types => ['Num'];        
    param [ 'x', 'y' ] => ( isa => Num, reader => 1, writer => 1, default => 0 );
}
 
package My::Point::FineGrained {
    use MooseX::Extended types => ['Int'];
    extends 'My::Point';
    param [ '+x', '+y' ] => ( isa => Int );
}
```

For many developers, the above looks rather reasonable. However, the Liskov Substitution Principle tells us that we should be able to use a subclass like its parent(s) (that's a gross oversimplification). That means I should be able to call `$point->set_x(3.14)` on both parent and child, but that's a fatal error for the child. Or making the child read-only when the parent is not would be another error. I could come up with plenty.

That being said, the problem is ubiquitous in Perl classes and the `'+x'` syntax is helpful enough that people probably want it. Shouldn't take too much hacking to fix. I think `MooseX::Extended::Core`'s `_add_attribute` would be the first place to look (the `param` and `field` functions are defined in that package, too).

Wanna submit a PR?

**Comment by gmbow** [comment]
> the Liskov Substitution Principle tells us that we should be able to use a subclass like its parent(s)

Yes I would agree on that. However as you mentioned there are actual use cases for that, like :

```perl
package My::Point {
    use MooseX::Extended types => ['Defined'];        
    param [ 'x', 'y' ] => ( isa => Defined );
}

package My::Point::Object {
    use MooseX::Extended types => ['Defined'];        
    param [ 'x', 'y' ] => ( isa => Object );
}
```
... And people just expect this to work as in Moose, regardless.

---

> Wanna submit a PR?

Sure, thanks for proposing! I took a quick look and I see that `param()` has the logic implemented [here](https://github.com/Ovid/moosex-extended/blob/main/lib/MooseX/Extended/Core.pm#L264). We might as well add the same instruction to method `field()` .
And : I couldn't find a test that exercices attribute inheritance, so I can create a new one for this.

**Comment by gmbow** [comment]
I started working on this : https://github.com/Ovid/moosex-extended/compare/main...gmbow:moosex-extended:issue-51.

Allowing the `+` syntax for `field` inheritance seems like a quick fix in the `Core`.
I built a very simple test script (`t/inheritance.t`) that compares the behavior of Moose and MooseX::Extended (I can see other tests you wrote that do so). It seems we have more issues to address. Eg, I get failures because :
- when a default is defined in an inherited `field` that is extended in a subclass, it does not apply in the subclass
- a type constraint on an in inherited `param` that extended in a subclass does not apply in the subclass

It seems this very much has to do with the `+` syntax, since inheritance without extension seems to behave properly.

Let me know what you think. The test case might be bugged, as well :).

```bash
$ prove -lv t/inheritance.t
t/inheritance.t ..
# Subtest: My::Point::Moose
    ok 1 - the parent class can be instantiated
    ok 2 - ... and the child class too
    ok 3 - the default param value is applied in the parent class
    ok 4 - ... and in the child class
    ok 5 - the child class can mutate its param
    ok 6 - ... but the parent can't
    ok 7 - the child class can mutate its field
    ok 8 - ... but the parent can't
    ok 9 - type constraint are enforced in the parent class
    ok 10 - ... and in the child class
    1..10
ok 1 - My::Point::Moose
# Subtest: My::Point
    ok 1 - the parent class can be instantiated
    ok 2 - ... and the child class too
    ok 3 - the default param value is applied in the parent class
    not ok 4 - ... and in the child class

    #   Failed test '... and in the child class'
    #   at t/inheritance.t line 38.
    #          got: undef
    #     expected: '0'
    ok 5 - the child class can mutate its param
    ok 6 - ... but the parent can't
    ok 7 - the child class can mutate its field
    ok 8 - ... but the parent can't
    ok 9 - type constraint are enforced in the parent class
    not ok 10 - ... and in the child class

    #   Failed test '... and in the child class'
    #   at t/inheritance.t line 50.
    # expecting: Regexp ((?^:Validation failed for 'Num'))
    # found: normal exit
    1..10
    # Looks like you failed 2 tests of 10.
not ok 2 - My::Point

#   Failed test 'My::Point'
#   at t/inheritance.t line 53.
1..2
# Looks like you failed 1 test of 2.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests

Test Summary Report
-------------------
t/inheritance.t (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=1, Tests=2,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.42 cusr  0.04 csys =  0.49 CPU)
Result: FAIL
$
```

**Comment by Ovid** [comment]
Thanks! Your test looks solid. Small nit: when you import a type, you don't need to quote it in the `isa` check:

```perl
    param 'x' => ( isa => Num, clearer => 1 );
```

I don't have the time to dig into this right now (tons of client work), but there's an undocumented trick you can use:

```perl
package My::Point  {
    use MooseX::Extended
        types => ['Num'],
        debug => 1;
    param 'x' => ( isa => Num, clearer => 1 );
    field 'y' => ( isa => Num, default => 0 );
}
```

Enabling `debug` gives you a ton of information dumped to your screen about what `MooseX::Extended` is doing under the hood. Might help you see the difference between Moose and MooseX::Extended here.

**Comment by Ovid** [comment]
I really need to learn Github better. Wasn't sure how to fork your fork to be able to submit a PR to it.

I found the bug and it was a bit tricky. In short, when we get to `$meta->add_attribute( $name, %opt_for );`, we need to still have the `+` sign on the name or else Moose doesn't know it's supposed to process an inherited attribute. However, we're generating a bunch of method names from the name, so we need to generate the method names from the name _without_ the leading plus sign, but call `add_attribute` _with_ the leading plus sign.

Also, in [`Moose::Meta::Attribute](https://github.com/moose/Moose/blob/master/lib/Moose/Meta/Attribute.pm#L175), we find the following:

```perl
sub illegal_options_for_inheritance {
    qw(reader writer accessor clearer predicate)
}
```

You're not allowed to override those in inheritance and you'll get an exception if you do.

The following patch fixes the issue and all tests pass.

```patch
diff --git a/lib/MooseX/Extended/Core.pm b/lib/MooseX/Extended/Core.pm
index b476c30..78478be 100644
--- a/lib/MooseX/Extended/Core.pm
+++ b/lib/MooseX/Extended/Core.pm
@@ -265,9 +265,11 @@ sub param ( $meta, $name, %opt_for ) {
 
     # "has [@attributes]" versus "has $attribute"
     foreach my $attr ( is_plain_arrayref($name) ? @$name : $name ) {
-        $attr =~ s/^\+//;      # in case they're overriding a parent class attribute
         my %options = %opt_for;    # copy each time to avoid overwriting
         $options{init_arg} //= $attr;
+
+        # in case they're inheriting an attribute
+        $options{init_arg} =~ s/\A\+//;
         _add_attribute( 'param', $meta, $attr, %options );
     }
 }
@@ -278,7 +280,6 @@ sub field ( $meta, $name, %opt_for ) {
 
     # "has [@attributes]" versus "has $attribute"
     foreach my $attr ( is_plain_arrayref($name) ? @$name : $name ) {
-        $attr =~ s/^\+//;      # in case they're overriding a parent class attribute        
         my %options = %opt_for;    # copy each time to avoid overwriting
         if ( defined( my $init_arg = $options{init_arg} ) ) {
             $init_arg =~ /\A_/ or throw_exception(
@@ -301,10 +302,17 @@ sub field ( $meta, $name, %opt_for ) {
 sub _add_attribute ( $attr_type, $meta, $name, %opt_for ) {
     _debug("Finalizing options for '$attr_type $name'");
 
+    # we use the $name to generate the other methods names. However,
+    # $orig_name is used to set the actual field name. This is because
+    # Moose allows `has '+x' => ( writer => 'set_x' );` to inherit an
+    # attribute from a parent class and only change the desired attribute
+    # options.
+    my $orig_name = $name;
+    $name =~ s/\A\+//;
     unless ( _is_valid_method_name($name) ) {
         throw_exception(
             'InvalidAttributeDefinition',
-            attribute_name => $name,
+            attribute_name => $orig_name,
             class_name     => $meta->name,
             messsage       => "Illegal attribute name, '$name'",
         );
@@ -337,9 +345,9 @@ sub _add_attribute ( $attr_type, $meta, $name, %opt_for ) {
         unless ( _is_valid_method_name( $opt_for{$option} ) ) {
             throw_exception(
                 'InvalidAttributeDefinition',
-                attribute_name => $name,
+                attribute_name => $orig_name,
                 class_name     => $meta->name,
-                messsage       => "Attribute '$name' has an invalid option name, $option => '$opt_for{$option}'",
+                messsage       => "Attribute '$orig_name' has an invalid option name, $option => '$opt_for{$option}'",
             );
         }
     }
@@ -370,8 +378,8 @@ sub _add_attribute ( $attr_type, $meta, $name, %opt_for ) {
     }
 
     delete $opt_for{_call_level};
-    _debug( "Setting $attr_type, '$name'", \%opt_for );
-    $meta->add_attribute( $name, %opt_for );
+    _debug( "Setting $attr_type, '$orig_name'", \%opt_for );
+    $meta->add_attribute( $orig_name, %opt_for );
 }
 
 sub _is_valid_method_name ($name) {
diff --git a/t/inheritance.t b/t/inheritance.t
index 92d1d24..53eca10 100644
--- a/t/inheritance.t
+++ b/t/inheritance.t
@@ -24,7 +24,7 @@ package My::Point  {
 package My::Point::Mutable {
     use MooseX::Extended;
     extends 'My::Point';
-    param '+x' => ( clearer => 1, writer => 1 );
+    param '+x' => ( writer => 1 );
     field '+y' => ( clearer => 1, writer => 1 );
 }
```

**Comment by Ovid** [comment]
Oh, and thank you for this! Not only is a great feature, I learned a few things new about Moose :)

**Comment by gmbow** [comment]
> I found the bug and it was a bit tricky. 

Ah that's great, thanks!
I had in mind that Moose wanted the `+` in `add_attribute` - but we I tried that the code started to break, I understand a bit better why now.

> Wasn't sure how to fork your fork to be able to submit a PR to it.

Maybe I can submit the new unit test in a PR, and then probably you can fetch the branch and add the `Core` patch to it before merging it.

**Comment by Ovid** [comment]
This is now released. Thank you!

**Comment by Ovid** [comment]
Meanwhile, I merged to `main` too quickly after it passed on my computer. CI is *not* happy with this: https://github.com/Ovid/moosex-extended/pull/57
